// DSA Master Sheet — must-solve LeetCode problems ordered pattern by pattern (solve in Java).
// Problem: [title, difficulty (E | M | H), leetcodeSlug, '*' when it is the anchor to learn the pattern's template on]

const LC_PREMIUM = new Set([
  'encode-and-decode-strings', 'meeting-rooms', 'meeting-rooms-ii', 'walls-and-gates',
  'graph-valid-tree', 'number-of-connected-components-in-an-undirected-graph', 'alien-dictionary',
]);

const RAW = [
  { title: 'Part 1: Arrays, Hashing & Strings', sections: [
    { title: '1.1 Hashing (HashMap / HashSet / int[26])', problems: [
      ['Contains Duplicate', 'E', 'contains-duplicate', '*'],
      ['Valid Anagram', 'E', 'valid-anagram'],
      ['Two Sum', 'E', 'two-sum', '*'],
      ['Group Anagrams', 'M', 'group-anagrams'],
      ['Top K Frequent Elements (bucket sort)', 'M', 'top-k-frequent-elements'],
      ['Encode and Decode Strings', 'M', 'encode-and-decode-strings'],
      ['Valid Sudoku', 'M', 'valid-sudoku'],
      ['Longest Consecutive Sequence', 'M', 'longest-consecutive-sequence'],
      ['Majority Element (Moore Voting)', 'E', 'majority-element'],
      ['Majority Element II', 'M', 'majority-element-ii'],
      ['Insert Delete GetRandom O(1)', 'M', 'insert-delete-getrandom-o1'],
    ] },
    { title: '1.2 Array techniques (in-place, Kadane, cyclic sort, matrix)', problems: [
      ['Remove Duplicates from Sorted Array', 'E', 'remove-duplicates-from-sorted-array', '*'],
      ['Move Zeroes', 'E', 'move-zeroes'],
      ['Rotate Array', 'M', 'rotate-array'],
      ['Best Time to Buy and Sell Stock', 'E', 'best-time-to-buy-and-sell-stock', '*'],
      ["Maximum Subarray (Kadane's)", 'M', 'maximum-subarray', '*'],
      ['Maximum Product Subarray', 'M', 'maximum-product-subarray'],
      ['Next Permutation', 'M', 'next-permutation'],
      ['Merge Sorted Array', 'E', 'merge-sorted-array'],
      ["Pascal's Triangle", 'E', 'pascals-triangle'],
      ['Set Mismatch (cyclic sort)', 'E', 'set-mismatch'],
      ['First Missing Positive (cyclic sort / index marking)', 'H', 'first-missing-positive'],
      ['Set Matrix Zeroes', 'M', 'set-matrix-zeroes'],
      ['Rotate Image', 'M', 'rotate-image'],
      ['Spiral Matrix', 'M', 'spiral-matrix'],
      ['Game of Life', 'M', 'game-of-life'],
    ] },
    { title: '1.3 Prefix sum (+ hashing)', problems: [
      ['Product of Array Except Self', 'M', 'product-of-array-except-self', '*'],
      ['Subarray Sum Equals K', 'M', 'subarray-sum-equals-k', '*'],
      ['Contiguous Array (longest subarray via prefix + first index)', 'M', 'contiguous-array'],
      ['Subarray Sums Divisible by K (count via prefix + frequency)', 'M', 'subarray-sums-divisible-by-k'],
      ['Range Sum Query 2D - Immutable (2D prefix sum)', 'M', 'range-sum-query-2d-immutable'],
      ['Car Pooling (difference array)', 'M', 'car-pooling'],
      ['Random Pick with Weight (prefix sum + binary search)', 'M', 'random-pick-with-weight'],
    ] },
    { title: '1.4 Two pointers', problems: [
      ['Valid Palindrome', 'E', 'valid-palindrome', '*'],
      ['Valid Palindrome II', 'E', 'valid-palindrome-ii'],
      ['Two Sum II - Input Array Is Sorted', 'M', 'two-sum-ii-input-array-is-sorted', '*'],
      ['3Sum', 'M', '3sum'],
      ['3Sum Closest', 'M', '3sum-closest'],
      ['4Sum', 'M', '4sum'],
      ['Container With Most Water', 'M', 'container-with-most-water'],
      ['Sort Colors (Dutch National Flag)', 'M', 'sort-colors'],
      ['Boats to Save People', 'M', 'boats-to-save-people'],
      ['Trapping Rain Water', 'H', 'trapping-rain-water'],
    ] },
    { title: '1.5 Sliding window (fixed, variable, atMost(K) - atMost(K-1))', problems: [
      ['Maximum Average Subarray I (fixed window)', 'E', 'maximum-average-subarray-i', '*'],
      ['Contains Duplicate II (window + HashSet)', 'E', 'contains-duplicate-ii'],
      ['Find All Anagrams in a String', 'M', 'find-all-anagrams-in-a-string'],
      ['Permutation in String', 'M', 'permutation-in-string'],
      ['Minimum Size Subarray Sum (variable window)', 'M', 'minimum-size-subarray-sum', '*'],
      ['Longest Substring Without Repeating Characters', 'M', 'longest-substring-without-repeating-characters'],
      ['Max Consecutive Ones III', 'M', 'max-consecutive-ones-iii'],
      ['Longest Repeating Character Replacement', 'M', 'longest-repeating-character-replacement'],
      ['Maximum Points You Can Obtain from Cards', 'M', 'maximum-points-you-can-obtain-from-cards'],
      ['Binary Subarrays With Sum (atMost trick)', 'M', 'binary-subarrays-with-sum', '*'],
      ['Count Number of Nice Subarrays', 'M', 'count-number-of-nice-subarrays'],
      ['Number of Substrings Containing All Three Characters', 'M', 'number-of-substrings-containing-all-three-characters'],
      ['Subarrays with K Different Integers', 'H', 'subarrays-with-k-different-integers'],
      ['Minimum Window Substring', 'H', 'minimum-window-substring'],
    ] },
    { title: '1.6 Strings (StringBuilder, expand around center)', problems: [
      ['Reverse Words in a String', 'M', 'reverse-words-in-a-string'],
      ['Longest Common Prefix', 'E', 'longest-common-prefix'],
      ['Isomorphic Strings', 'E', 'isomorphic-strings'],
      ['Sort Characters By Frequency', 'M', 'sort-characters-by-frequency'],
      ['String to Integer (atoi)', 'M', 'string-to-integer-atoi'],
      ['Roman to Integer', 'E', 'roman-to-integer'],
      ['Integer to Roman', 'M', 'integer-to-roman'],
      ['Zigzag Conversion', 'M', 'zigzag-conversion'],
      ['String Compression', 'M', 'string-compression'],
      ['Longest Palindromic Substring', 'M', 'longest-palindromic-substring', '*'],
      ['Palindromic Substrings', 'M', 'palindromic-substrings'],
    ] },
  ] },
  { title: 'Part 2: Sorting & Binary Search', sections: [
    { title: '2.1 Sorting (merge sort, quick sort)', problems: [
      ['Sort an Array (implement merge sort AND quick sort)', 'M', 'sort-an-array', '*'],
      ['Largest Number (custom comparator)', 'M', 'largest-number'],
      ['Count of Smaller Numbers After Self (count inversions with merge sort)', 'H', 'count-of-smaller-numbers-after-self'],
      ['Reverse Pairs', 'H', 'reverse-pairs'],
    ] },
    { title: '2.2 Binary search on arrays', problems: [
      ['Binary Search', 'E', 'binary-search', '*'],
      ['Search Insert Position (lower bound)', 'E', 'search-insert-position'],
      ['Find First and Last Position of Element', 'M', 'find-first-and-last-position-of-element-in-sorted-array', '*'],
      ['Search in Rotated Sorted Array', 'M', 'search-in-rotated-sorted-array'],
      ['Find Minimum in Rotated Sorted Array', 'M', 'find-minimum-in-rotated-sorted-array'],
      ['Single Element in a Sorted Array', 'M', 'single-element-in-a-sorted-array'],
      ['Find Peak Element', 'M', 'find-peak-element'],
      ['Search a 2D Matrix', 'M', 'search-a-2d-matrix'],
      ['Search a 2D Matrix II', 'M', 'search-a-2d-matrix-ii'],
      ['Time Based Key-Value Store', 'M', 'time-based-key-value-store'],
      ['Median of Two Sorted Arrays', 'H', 'median-of-two-sorted-arrays'],
    ] },
    { title: '2.3 Binary search on the answer', problems: [
      ['Sqrt(x)', 'E', 'sqrtx', '*'],
      ['Koko Eating Bananas', 'M', 'koko-eating-bananas', '*'],
      ['Minimum Number of Days to Make m Bouquets', 'M', 'minimum-number-of-days-to-make-m-bouquets'],
      ['Capacity To Ship Packages Within D Days', 'M', 'capacity-to-ship-packages-within-d-days'],
      ['Find the Smallest Divisor Given a Threshold', 'M', 'find-the-smallest-divisor-given-a-threshold'],
      ['Magnetic Force Between Two Balls (= Aggressive Cows)', 'M', 'magnetic-force-between-two-balls'],
      ['Kth Smallest Element in a Sorted Matrix', 'M', 'kth-smallest-element-in-a-sorted-matrix'],
      ["Split Array Largest Sum (= Book Allocation / Painter's Partition)", 'H', 'split-array-largest-sum'],
    ] },
  ] },
  { title: 'Part 3: Stack & Monotonic Stack', sections: [
    { title: '3.1 Stack', problems: [
      ['Valid Parentheses', 'E', 'valid-parentheses', '*'],
      ['Min Stack', 'M', 'min-stack'],
      ['Implement Queue using Stacks', 'E', 'implement-queue-using-stacks'],
      ['Design Circular Queue', 'M', 'design-circular-queue'],
      ['Evaluate Reverse Polish Notation', 'M', 'evaluate-reverse-polish-notation'],
      ['Minimum Remove to Make Valid Parentheses', 'M', 'minimum-remove-to-make-valid-parentheses'],
      ['Decode String', 'M', 'decode-string'],
      ['Basic Calculator II', 'M', 'basic-calculator-ii'],
      ['Basic Calculator', 'H', 'basic-calculator'],
      ['Longest Valid Parentheses', 'H', 'longest-valid-parentheses'],
      ['Asteroid Collision', 'M', 'asteroid-collision'],
      ['Car Fleet', 'M', 'car-fleet'],
    ] },
    { title: '3.2 Monotonic stack / deque', problems: [
      ['Next Greater Element I', 'E', 'next-greater-element-i', '*'],
      ['Final Prices With a Special Discount in a Shop', 'E', 'final-prices-with-a-special-discount-in-a-shop'],
      ['Next Greater Element II', 'M', 'next-greater-element-ii'],
      ['Daily Temperatures', 'M', 'daily-temperatures'],
      ['Online Stock Span', 'M', 'online-stock-span'],
      ['Sum of Subarray Minimums', 'M', 'sum-of-subarray-minimums'],
      ['Remove K Digits', 'M', 'remove-k-digits'],
      ['Largest Rectangle in Histogram', 'H', 'largest-rectangle-in-histogram'],
      ['Maximal Rectangle', 'H', 'maximal-rectangle'],
      ['Sliding Window Maximum (monotonic deque)', 'H', 'sliding-window-maximum'],
    ] },
  ] },
  { title: 'Part 4: Linked List', sections: [
    { title: '4.1 Linked list (reversal, fast/slow pointers, dummy node)', problems: [
      ['Reverse Linked List (iterative + recursive)', 'E', 'reverse-linked-list', '*'],
      ['Reverse Linked List II', 'M', 'reverse-linked-list-ii'],
      ['Middle of the Linked List', 'E', 'middle-of-the-linked-list', '*'],
      ['Merge Two Sorted Lists', 'E', 'merge-two-sorted-lists'],
      ['Linked List Cycle', 'E', 'linked-list-cycle'],
      ['Linked List Cycle II', 'M', 'linked-list-cycle-ii'],
      ['Palindrome Linked List', 'E', 'palindrome-linked-list'],
      ['Intersection of Two Linked Lists', 'E', 'intersection-of-two-linked-lists'],
      ['Remove Nth Node From End of List', 'M', 'remove-nth-node-from-end-of-list'],
      ['Reorder List', 'M', 'reorder-list'],
      ['Add Two Numbers', 'M', 'add-two-numbers'],
      ['Sort List', 'M', 'sort-list'],
      ['Rotate List', 'M', 'rotate-list'],
      ['Copy List with Random Pointer', 'M', 'copy-list-with-random-pointer'],
      ['Flatten a Multilevel Doubly Linked List', 'M', 'flatten-a-multilevel-doubly-linked-list'],
      ['Find the Duplicate Number', 'M', 'find-the-duplicate-number'],
      ['Reverse Nodes in k-Group', 'H', 'reverse-nodes-in-k-group'],
    ] },
    { title: '4.2 Design with linked lists + hash maps', problems: [
      ['LRU Cache', 'M', 'lru-cache', '*'],
      ['LFU Cache', 'H', 'lfu-cache'],
    ] },
  ] },
  { title: 'Part 5: Recursion, Backtracking & Bits', sections: [
    { title: '5.1 Recursion & backtracking (pick / not-pick, for-loop choice)', problems: [
      ['Pow(x, n)', 'M', 'powx-n', '*'],
      ['Subsets', 'M', 'subsets', '*'],
      ['Subsets II', 'M', 'subsets-ii'],
      ['Combination Sum', 'M', 'combination-sum'],
      ['Combination Sum II', 'M', 'combination-sum-ii'],
      ['Combination Sum III', 'M', 'combination-sum-iii'],
      ['Permutations', 'M', 'permutations'],
      ['Permutations II', 'M', 'permutations-ii'],
      ['Generate Parentheses', 'M', 'generate-parentheses'],
      ['Letter Combinations of a Phone Number', 'M', 'letter-combinations-of-a-phone-number'],
      ['Palindrome Partitioning', 'M', 'palindrome-partitioning'],
      ['Word Search', 'M', 'word-search'],
      ['Beautiful Arrangement', 'M', 'beautiful-arrangement'],
      ['Partition to K Equal Sum Subsets (backtracking + bitmask)', 'M', 'partition-to-k-equal-sum-subsets'],
      ['N-Queens', 'H', 'n-queens'],
      ['Sudoku Solver', 'H', 'sudoku-solver'],
    ] },
    { title: '5.2 Bit manipulation', problems: [
      ['Single Number', 'E', 'single-number', '*'],
      ['Number of 1 Bits', 'E', 'number-of-1-bits'],
      ['Counting Bits', 'E', 'counting-bits'],
      ['Reverse Bits', 'E', 'reverse-bits'],
      ['Missing Number', 'E', 'missing-number'],
      ['Add Binary', 'E', 'add-binary'],
      ['Single Number II', 'M', 'single-number-ii'],
      ['Single Number III', 'M', 'single-number-iii'],
      ['Sum of Two Integers', 'M', 'sum-of-two-integers'],
    ] },
  ] },
  { title: 'Part 6: Heap, Intervals & Greedy', sections: [
    { title: '6.1 Heap / Top-K (PriorityQueue)', problems: [
      ['Kth Largest Element in a Stream', 'E', 'kth-largest-element-in-a-stream', '*'],
      ['Last Stone Weight', 'E', 'last-stone-weight'],
      ['K Closest Points to Origin', 'M', 'k-closest-points-to-origin'],
      ['Kth Largest Element in an Array', 'M', 'kth-largest-element-in-an-array'],
      ['Task Scheduler', 'M', 'task-scheduler'],
      ['Reorganize String', 'M', 'reorganize-string'],
      ['Hand of Straights', 'M', 'hand-of-straights'],
      ['Merge k Sorted Lists', 'H', 'merge-k-sorted-lists'],
      ['Find K Pairs with Smallest Sums (k-way merge)', 'M', 'find-k-pairs-with-smallest-sums'],
      ['Design Twitter', 'M', 'design-twitter'],
      ['Find Median from Data Stream (two heaps)', 'H', 'find-median-from-data-stream'],
    ] },
    { title: '6.2 Intervals & line sweep (sort by start / end)', problems: [
      ['Merge Intervals', 'M', 'merge-intervals', '*'],
      ['Insert Interval', 'M', 'insert-interval'],
      ['Non-overlapping Intervals', 'M', 'non-overlapping-intervals'],
      ['Remove Covered Intervals', 'M', 'remove-covered-intervals'],
      ['Minimum Number of Arrows to Burst Balloons', 'M', 'minimum-number-of-arrows-to-burst-balloons'],
      ['Interval List Intersections', 'M', 'interval-list-intersections'],
      ['Meeting Rooms', 'E', 'meeting-rooms'],
      ['Meeting Rooms II', 'M', 'meeting-rooms-ii'],
      ['Minimum Interval to Include Each Query', 'H', 'minimum-interval-to-include-each-query'],
      ['The Skyline Problem (line sweep + heap)', 'H', 'the-skyline-problem'],
    ] },
    { title: '6.3 Greedy', problems: [
      ['Assign Cookies', 'E', 'assign-cookies', '*'],
      ['Can Place Flowers', 'E', 'can-place-flowers'],
      ['Jump Game', 'M', 'jump-game', '*'],
      ['Jump Game II', 'M', 'jump-game-ii'],
      ['Gas Station', 'M', 'gas-station'],
      ['Partition Labels', 'M', 'partition-labels'],
      ['Merge Triplets to Form Target Triplet', 'M', 'merge-triplets-to-form-target-triplet'],
      ['Valid Parenthesis String', 'M', 'valid-parenthesis-string'],
      ['Candy', 'H', 'candy'],
    ] },
  ] },
  { title: 'Part 7: Trees', sections: [
    { title: '7.1 Binary tree DFS', problems: [
      ['Binary Tree Inorder Traversal (recursive + iterative)', 'E', 'binary-tree-inorder-traversal', '*'],
      ['Invert Binary Tree', 'E', 'invert-binary-tree'],
      ['Maximum Depth of Binary Tree', 'E', 'maximum-depth-of-binary-tree', '*'],
      ['Same Tree', 'E', 'same-tree'],
      ['Symmetric Tree', 'E', 'symmetric-tree'],
      ['Diameter of Binary Tree', 'E', 'diameter-of-binary-tree'],
      ['Balanced Binary Tree', 'E', 'balanced-binary-tree'],
      ['Subtree of Another Tree', 'E', 'subtree-of-another-tree'],
      ['Path Sum II', 'M', 'path-sum-ii'],
      ['Path Sum III (prefix sum on a tree)', 'M', 'path-sum-iii'],
      ['Count Good Nodes in Binary Tree', 'M', 'count-good-nodes-in-binary-tree'],
      ['Lowest Common Ancestor of a Binary Tree', 'M', 'lowest-common-ancestor-of-a-binary-tree'],
      ['House Robber III (tree DP)', 'M', 'house-robber-iii'],
      ['Binary Tree Maximum Path Sum', 'H', 'binary-tree-maximum-path-sum'],
      ['Construct Binary Tree from Preorder and Inorder', 'M', 'construct-binary-tree-from-preorder-and-inorder-traversal'],
      ['Flatten Binary Tree to Linked List', 'M', 'flatten-binary-tree-to-linked-list'],
      ['Serialize and Deserialize Binary Tree', 'H', 'serialize-and-deserialize-binary-tree'],
    ] },
    { title: '7.2 Binary tree BFS & views', problems: [
      ['Binary Tree Level Order Traversal', 'M', 'binary-tree-level-order-traversal', '*'],
      ['Binary Tree Zigzag Level Order Traversal', 'M', 'binary-tree-zigzag-level-order-traversal'],
      ['Binary Tree Right Side View', 'M', 'binary-tree-right-side-view'],
      ['Populating Next Right Pointers in Each Node', 'M', 'populating-next-right-pointers-in-each-node'],
      ['Maximum Width of Binary Tree', 'M', 'maximum-width-of-binary-tree'],
      ['Vertical Order Traversal of a Binary Tree', 'H', 'vertical-order-traversal-of-a-binary-tree'],
      ['All Nodes Distance K in Binary Tree', 'M', 'all-nodes-distance-k-in-binary-tree'],
      ['Amount of Time for Binary Tree to Be Infected', 'M', 'amount-of-time-for-binary-tree-to-be-infected'],
    ] },
    { title: '7.3 Binary search tree', problems: [
      ['Convert Sorted Array to Binary Search Tree', 'E', 'convert-sorted-array-to-binary-search-tree'],
      ['Insert into a Binary Search Tree', 'M', 'insert-into-a-binary-search-tree', '*'],
      ['Delete Node in a BST', 'M', 'delete-node-in-a-bst'],
      ['Validate Binary Search Tree', 'M', 'validate-binary-search-tree'],
      ['Kth Smallest Element in a BST', 'M', 'kth-smallest-element-in-a-bst'],
      ['Lowest Common Ancestor of a BST', 'M', 'lowest-common-ancestor-of-a-binary-search-tree'],
      ['Construct BST from Preorder Traversal', 'M', 'construct-binary-search-tree-from-preorder-traversal'],
      ['Binary Search Tree Iterator', 'M', 'binary-search-tree-iterator'],
    ] },
    { title: '7.4 Tries', problems: [
      ['Implement Trie (Prefix Tree)', 'M', 'implement-trie-prefix-tree', '*'],
      ['Design Add and Search Words Data Structure', 'M', 'design-add-and-search-words-data-structure'],
      ['Word Search II', 'H', 'word-search-ii'],
      ['Maximum XOR of Two Numbers in an Array', 'M', 'maximum-xor-of-two-numbers-in-an-array'],
    ] },
  ] },
  { title: 'Part 8: Graphs', sections: [
    { title: '8.1 BFS / DFS (grids + adjacency lists)', problems: [
      ['Flood Fill', 'E', 'flood-fill'],
      ['Number of Islands', 'M', 'number-of-islands', '*'],
      ['Max Area of Island', 'M', 'max-area-of-island'],
      ['Number of Provinces', 'M', 'number-of-provinces'],
      ['Clone Graph', 'M', 'clone-graph'],
      ['Rotting Oranges (multi-source BFS)', 'M', 'rotting-oranges', '*'],
      ['01 Matrix', 'M', '01-matrix'],
      ['Walls and Gates', 'M', 'walls-and-gates'],
      ['Surrounded Regions', 'M', 'surrounded-regions'],
      ['Pacific Atlantic Water Flow', 'M', 'pacific-atlantic-water-flow'],
      ['Is Graph Bipartite?', 'M', 'is-graph-bipartite'],
      ['Evaluate Division (weighted graph)', 'M', 'evaluate-division'],
      ['Snakes and Ladders', 'M', 'snakes-and-ladders'],
      ['Open the Lock (BFS on states)', 'M', 'open-the-lock'],
      ['Word Ladder', 'H', 'word-ladder'],
    ] },
    { title: "8.2 Topological sort (Kahn's BFS + DFS)", problems: [
      ['Course Schedule', 'M', 'course-schedule', '*'],
      ['Course Schedule II', 'M', 'course-schedule-ii'],
      ['Find Eventual Safe States', 'M', 'find-eventual-safe-states'],
      ['Alien Dictionary', 'H', 'alien-dictionary'],
    ] },
    { title: '8.3 Union-Find (DSU: rank / size + path compression)', problems: [
      ['Number of Connected Components in an Undirected Graph', 'M', 'number-of-connected-components-in-an-undirected-graph', '*'],
      ['Graph Valid Tree', 'M', 'graph-valid-tree'],
      ['Redundant Connection', 'M', 'redundant-connection'],
      ['Number of Operations to Make Network Connected', 'M', 'number-of-operations-to-make-network-connected'],
      ['Accounts Merge', 'M', 'accounts-merge'],
      ['Making A Large Island', 'H', 'making-a-large-island'],
    ] },
    { title: '8.4 Shortest paths (BFS, Dijkstra, Bellman-Ford, Floyd-Warshall)', problems: [
      ['Shortest Path in Binary Matrix', 'M', 'shortest-path-in-binary-matrix', '*'],
      ['Network Delay Time (Dijkstra)', 'M', 'network-delay-time', '*'],
      ['Path With Minimum Effort', 'M', 'path-with-minimum-effort'],
      ['Cheapest Flights Within K Stops (Bellman-Ford)', 'M', 'cheapest-flights-within-k-stops'],
      ['Find the City With the Smallest Number of Neighbors (Floyd-Warshall)', 'M', 'find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance'],
      ['Swim in Rising Water', 'H', 'swim-in-rising-water'],
    ] },
    { title: '8.5 MST & advanced', problems: [
      ["Min Cost to Connect All Points (Prim's + Kruskal's)", 'M', 'min-cost-to-connect-all-points', '*'],
      ['Reconstruct Itinerary (Eulerian path)', 'H', 'reconstruct-itinerary'],
      ['Critical Connections in a Network (bridges)', 'H', 'critical-connections-in-a-network'],
      ['Minimum Edge Reversals So Every Node Is Reachable (re-rooting)', 'H', 'minimum-edge-reversals-so-every-node-is-reachable'],
    ] },
  ] },
  { title: 'Part 9: Dynamic Programming', sections: [
    { title: '9.1 1D DP (recursion → memo → tabulation → space-optimised)', problems: [
      ['Fibonacci Number (memo → tabulation)', 'E', 'fibonacci-number'],
      ['Climbing Stairs', 'E', 'climbing-stairs', '*'],
      ['Min Cost Climbing Stairs', 'E', 'min-cost-climbing-stairs'],
      ['House Robber', 'M', 'house-robber', '*'],
      ['House Robber II', 'M', 'house-robber-ii'],
      ['Decode Ways', 'M', 'decode-ways'],
      ['Word Break', 'M', 'word-break'],
      ['Unique Binary Search Trees (Catalan)', 'M', 'unique-binary-search-trees'],
    ] },
    { title: '9.2 Grid / 2D DP', problems: [
      ['Unique Paths', 'M', 'unique-paths', '*'],
      ['Unique Paths II', 'M', 'unique-paths-ii'],
      ['Minimum Path Sum', 'M', 'minimum-path-sum'],
      ['Triangle', 'M', 'triangle'],
      ['Maximal Square', 'M', 'maximal-square'],
      ['Count Square Submatrices with All Ones', 'M', 'count-square-submatrices-with-all-ones'],
      ['Cherry Pickup II (3D DP)', 'H', 'cherry-pickup-ii'],
      ['Longest Increasing Path in a Matrix', 'H', 'longest-increasing-path-in-a-matrix'],
    ] },
    { title: '9.3 Knapsack / subset DP', problems: [
      ['Ones and Zeroes (0/1 knapsack)', 'M', 'ones-and-zeroes', '*'],
      ['Partition Equal Subset Sum', 'M', 'partition-equal-subset-sum'],
      ['Last Stone Weight II (min subset-sum difference)', 'M', 'last-stone-weight-ii'],
      ['Target Sum', 'M', 'target-sum'],
      ['Coin Change', 'M', 'coin-change'],
      ['Coin Change II (unbounded knapsack)', 'M', 'coin-change-ii'],
      ['Perfect Squares', 'M', 'perfect-squares'],
      ['Combination Sum IV (ordered counting)', 'M', 'combination-sum-iv'],
    ] },
    { title: '9.4 DP on strings', problems: [
      ['Longest Common Subsequence', 'M', 'longest-common-subsequence', '*'],
      ['Longest Palindromic Subsequence', 'M', 'longest-palindromic-subsequence'],
      ['Minimum Insertion Steps to Make a String Palindrome', 'H', 'minimum-insertion-steps-to-make-a-string-palindrome'],
      ['Shortest Common Supersequence', 'H', 'shortest-common-supersequence'],
      ['Distinct Subsequences', 'H', 'distinct-subsequences'],
      ['Edit Distance', 'M', 'edit-distance'],
      ['Interleaving String', 'M', 'interleaving-string'],
      ['Wildcard Matching', 'H', 'wildcard-matching'],
      ['Regular Expression Matching', 'H', 'regular-expression-matching'],
    ] },
    { title: '9.5 DP on stocks (buy/sell state machine)', problems: [
      ['Best Time to Buy and Sell Stock II', 'M', 'best-time-to-buy-and-sell-stock-ii', '*'],
      ['Best Time to Buy and Sell Stock IV', 'H', 'best-time-to-buy-and-sell-stock-iv'],
      ['Best Time to Buy and Sell Stock with Cooldown', 'M', 'best-time-to-buy-and-sell-stock-with-cooldown'],
      ['Best Time to Buy and Sell Stock with Transaction Fee', 'M', 'best-time-to-buy-and-sell-stock-with-transaction-fee'],
    ] },
    { title: '9.6 LIS (DP + binary search)', problems: [
      ['Longest Increasing Subsequence', 'M', 'longest-increasing-subsequence', '*'],
      ['Largest Divisible Subset', 'M', 'largest-divisible-subset'],
      ['Longest String Chain', 'M', 'longest-string-chain'],
      ['Russian Doll Envelopes', 'H', 'russian-doll-envelopes'],
    ] },
    { title: '9.7 Partition / interval DP (MCM)', problems: [
      ['Minimum Cost to Cut a Stick', 'H', 'minimum-cost-to-cut-a-stick', '*'],
      ['Burst Balloons', 'H', 'burst-balloons'],
      ['Palindrome Partitioning II', 'H', 'palindrome-partitioning-ii'],
      ['Partition Array for Maximum Sum', 'M', 'partition-array-for-maximum-sum'],
    ] },
  ] },
  { title: 'Part 10: Math, String Matching, Advanced Structures & Concurrency', sections: [
    { title: '10.1 Math & geometry', problems: [
      ['Happy Number', 'E', 'happy-number'],
      ['Palindrome Number', 'E', 'palindrome-number'],
      ['Plus One', 'E', 'plus-one'],
      ['Reverse Integer (overflow)', 'M', 'reverse-integer'],
      ['Multiply Strings', 'M', 'multiply-strings'],
      ['Detect Squares', 'M', 'detect-squares'],
      ['Count Primes (Sieve of Eratosthenes)', 'M', 'count-primes'],
    ] },
    { title: '10.2 String matching (KMP / LPS)', problems: [
      ['Find the Index of the First Occurrence in a String (KMP)', 'E', 'find-the-index-of-the-first-occurrence-in-a-string', '*'],
      ['Longest Happy Prefix', 'H', 'longest-happy-prefix'],
    ] },
    { title: '10.3 Ordered maps & segment tree / Fenwick tree', problems: [
      ['My Calendar I (TreeMap floor/ceiling)', 'M', 'my-calendar-i'],
      ['Range Sum Query - Mutable (segment tree / BIT)', 'M', 'range-sum-query-mutable', '*'],
    ] },
    { title: '10.4 Concurrency in Java (threads, locks, semaphores)', problems: [
      ['Print in Order', 'E', 'print-in-order', '*'],
      ['Print FooBar Alternately', 'M', 'print-foobar-alternately'],
    ] },
  ] },
];

export const DIFFICULTY_LABEL = { E: 'Easy', M: 'Medium', H: 'Hard' };

export function leetcodeUrl(slug) {
  return `https://leetcode.com/problems/${slug}/`;
}

export function videoSearchUrl(title) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${title} leetcode solution`)}`;
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80);
}

export const DSA_MASTER = RAW.map((part, pi) => {
  const partId = `m${pi + 1}`;
  return {
    id: partId,
    title: part.title,
    sections: part.sections.map((section, si) => {
      const sectionId = `${partId}-l${si + 1}`;
      return {
        id: sectionId,
        title: section.title,
        problems: section.problems.map(([title, difficulty, lc, anchor]) => ({
          id: `${sectionId}-${slugify(title)}`,
          title,
          difficulty,
          leetcode: lc,
          premium: LC_PREMIUM.has(lc),
          anchor: anchor === '*',
        })),
      };
    }),
  };
});

export const DSA_MASTER_TOTAL = DSA_MASTER.reduce(
  (sum, part) => sum + part.sections.reduce((s, sec) => s + sec.problems.length, 0), 0
);
